### ISSUE TITLE
[Idea] [Modbus Etrel Inch] UniqueIds and state_class

### ISSUE THREAD

**Issue by Ztarbox** [GiZMoSK1221/hass-addons#24]
Hi,

I am also playing around with integrating the etrel inch using modbus.

As some small Ideas for your modbus sensors:
* Add the "unique_id" property to every sensor. This way in HASS you can do changes and add them to an area.
* Also I am playing around with [state_class](https://developers.home-assistant.io/docs/core/entity/sensor?_highlight=measure#available-state-classes) to enable energy statistics.
```
- name: Wallbox Total imported active energy in running session
  unit_of_measurement: kWh
  slave: 255
  address: 30
  input_type: input
  data_type: float32
  precision: 2
  device_class: energy
  unique_id: etrel_totelImportedEnergyInSession
  state_class: measurement
```

**Comment by GiZMoSK1221** [comment]
- Add the "unique_id" property to every sensor.  - DONE
- Also I am playing around with [state_class] to enable energy statistics.
added my latest version. There I have state_class defined.
