### ISSUE TITLE
grid connection status for sunsynk power flow card

### ISSUE THREAD

**Issue by user86000** [GiZMoSK1221/hass-addons#26]
wattsonic.yaml:

template:
  binary_sensor:
      - name: "wattsonic_grid_connected"
        state: >
          {% set w1 = states('sensor.wattsonic_inverter_running_status') %}
          {% if w1 == '2' %} 1
          {% else %} 0
          {% endif %}

sunsynk.yaml line 44:

  grid_connected_status_194: binary_sensor.wattsonic_grid_connected

**Comment by GiZMoSK1221** [comment]
thank you!, updated sources
