### ISSUE TITLE
better soluteion fot displaying RTC and firmware

### ISSUE THREAD

**Issue by user86000** [GiZMoSK1221/hass-addons#27]
structure: ">BBBB"

for adress 10011 and 10013 (firmware version)
result: 22,46,2,0 and 1,0,0,0

**Comment by GiZMoSK1221** [comment]
thank you!, updated sources
especially for the register 10013, it is not described. Do you have a newer version of modbus protocol?

**Comment by user86000** [comment]
i have a m-tec energybutler gen.3, hardware is identical with wattsonic and a-tronix

i found this modbus register from different wattsonic forums:

[Register.xlsx](https://github.com/GiZMoSK1221/hass-addons/files/13704633/Register.xlsx)
