### ISSUE TITLE
sunways modified version

### ISSUE THREAD

**Issue by halentech** [GiZMoSK1221/hass-addons#31]
I have sunways (wattsonic) inverter and used your version. Modified to correctly display frequency of grid, from 500Hz to 50Hz and added missing modbus registers.
[sunways.zip](https://github.com/GiZMoSK1221/hass-addons/files/14067700/sunways.zip)

**Comment by GiZMoSK1221** [comment]
source updated. Thank you

**Comment by GiZMoSK1221** [comment]
done
