### ISSUE TITLE
oAuth when running script in standalone mode

### ISSUE THREAD

**Issue by Raemsna** [GiZMoSK1221/hass-addons#47]
Sorry for dumb question. 

As I have installed homeassistant over docker, I cannot install the add-on directly. 
However I have read that there is the possibility to run the script in "standalone mode" without adding the add-on by just running it.

I have done as written, included the options and stations file in the same folder and changed the options according to my setup. 

However I do not know, how I shall get the url for the oAuth section as written in the FAQ. 

I assume that's why I get this error: 

`Run mode: local
Config dir:
29.09.2024 17:15:49 Connected to mqtt broker
29.09.2024 17:15:49 Connected to mqtt broker - mqtt_on_connect
Netatmo authorization_code: Wrong response code 400`

my options.yaml: 

`netatmo:
    client_id: "xxSuperSecretxx"
    client_secret: "xxSuperSecretxx"
    refresh_interval: 2                     #refresh time in minutes
    oauth_code: "yy"
    redirect_uri: "hassio"
    state: "nfws_hass"                      #SOME_ARBITRARY_BUT_UNIQUE_STRING
    show_response: "True"
    #granted rights can be checked here: https://home.netatmo.com/settings/my-account
    #documentation: https://dev.netatmo.com/apidocumentation/oauth#errors
    #apps: https://dev.netatmo.com/apps/
mqtt:
    address: "192.168.0.xxx"
    port: 1884
    username: "mosquitto"
    password: "xxSuperSecretxx"
    client: "nwsclient12"
nfws:
    deleteRetain: True                      #deletes all nfws retained configuration messages on start, default= False
    log_level: debug                        #normal or debug`

Thank you very much for your help! 

BR

**Comment by GiZMoSK1221** [comment]
did you get to this screen?
![](https://raw.githubusercontent.com/GiZMoSK1221/hass-addons/main/nfws/help/netatmo_accept_code.jpg)
oauth is in url after code=

to response code 400, couple weeks ago, I tested the installation manual, if it works, and i also got once code 400. I suppose it was because I didn't stop the addon after first run.

**Comment by GiZMoSK1221** [comment]
and where are stored your stations.yaml, netatmo_token.yaml and options.yaml ? and you are just executing py nfws.py ?

**Comment by Raemsna** [comment]
So, I run homeassistant and also nfws.py from a home server without graphical user interface. 

stations.yaml, options.yaml and nfws.py are located in the same folder
netatmo_token.yaml is MISSING (do I need to create it myself or is it normalle generated by script)? 

to simulate I have opened the oauth request in browser on a separate machine with code => "Access Token" from netatmo dev homepage. Result like this. 

![Unbenannt](https://github.com/user-attachments/assets/65f4098f-6c3c-4d7e-a945-0f7ebc407311)

I think I have a know in my brain :(

BR
Raemsna

**Comment by GiZMoSK1221** [comment]
I'm glad to hear, that it works.
